#!/usr/bin/env python3

"""
A solution to a ROSALIND bioinformatics problem.
Problem Title: Compute the Number of Times a Pattern Appears in a Text
Rosalind ID: BA1A
URL: http://rosalind.info/problems/ba1a/
"""

def number_of_patterns(text,pattern):
  count = 0
  for i in range(0,len(text) - len(pattern) + 1):
    if text[i:(i+len(pattern))] == pattern:
      count= count + 1
  return count



    
