#!/usr/bin/env python3

"""
A solution to a ROSALIND bioinformatics problem.
Problem Title: Find the reverse complement of a DNA string
Rosalind ID: BA1C
URL: http://rosalind.info/problems/ba1c/
"""


def complement(text):
  comp=""
  for i in range(0,len(text)):
    if text[i] == "A":
      comp = comp + "T"
    elif text[i] == "T":
      comp = comp + "A"
    elif text[i] == "G":
      comp = comp + "C"
    else:
      comp = comp + "G"
  return comp

def reverse(text):
  return text[::-1]

if __name__ == '__main__':
    x="CTAGTGACT"
    print (str(reverse(complement(x))))
