#!/usr/bin/env python3

"""
A solution to a ROSALIND bioinformatics problem.
Problem Title: Compute the Hamming Distance Between Two Strings
Rosalind ID: BA1G
URL: http://rosalind.info/problems/ba1g
"""

def HammingDistance(p, q):
    """Computes the hamming distance between strings p and q"""
    if len(p) != len(q):
        return -1

    dist = 0
    #zip(AB,CD) gives (('A','C'),('B','D'))
    for first, second in zip(p, q):
        if first != second:
            dist = dist + 1

    return dist


if __name__ == '__main__':
    x='''GGGCCGTTGGT
GGACCGTTGAC'''
    inlines=x.split("\n")
    p = inlines[0]
    q = inlines[1]
    print(HammingDistance(p,q))
