#!/usr/bin/env python3

"""
A solution to a ROSALIND bioinformatics problem.
Problem Title: Translate an RNA String into an Amino Acid String
Rosalind ID: BA4A
URL: http://rosalind.info/problems/ba4a/
"""

def translation(rna_pattern):
    amino='''AAAK
AACN
AAGK
AAUN
ACAT
ACCT
ACGT
ACUT
AGAR
AGCS
AGGR
AGUS
AUAI
AUCI
AUGM
AUUI
CAAQ
CACH
CAGQ
CAUH
CCAP
CCCP
CCGP
CCUP
CGAR
CGCR
CGGR
CGUR
CUAL
CUCL
CUGL
CUUL
GAAE
GACD
GAGE
GAUD
GCAA
GCCA
GCGA
GCUA
GGAG
GGCG
GGGG
GGUG
GUAV
GUCV
GUGV
GUUV
UAA*
UACY
UAG*
UAUY
UCAS
UCCS
UCGS
UCUS
UGA*
UGCC
UGGW
UGUC
UUAL
UUCF
UUGL
UUUF'''.split('\n')
    #keys are 3-mers
    amino_dict = dict()
    for a in amino:
        amino_dict[a[0:3]]=a[3]
    peptide=''
    for i in range (0,len(rna_pattern),3):
        if amino_dict[rna_pattern[i:i+3]]=='*':
            break
        else:
            peptide=peptide+amino_dict[rna_pattern[i:i+3]]
    return peptide


if __name__ == '__main__':

    x='''AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA'''
    res=translation(x)
    print(res)
    print(res == 'MAMAPRTEINSTRING')
