#!/usr/bin/env python3

"""
A solution to a ROSALIND bioinformatics problem.
Problem Title: Implement GreedySorting to Sort a Permutation by Reversals
Rosalind ID: BA6B
URL: http://rosalind.info/problems/ba6b/
"""
def breakPoints(P):
    n=0
    for i in range (len(P)-1):
        if (P[i+1]-P[i])!=1:
            n=n+1
    return n

if __name__ == '__main__':
    x = '''(+3 +4 +5 -12 -8 -7 -6 +1 +2 +10 +9 -11 +13 +14)'''
    P = [0]
    S = x.split(" ")
    P = P + S
    P[1] = P[1][1:]
    P[len(P) - 1] = P[len(P) - 1][:-1]
    for i in range(1, len(P)):
        P[i] = int(P[i])
    P.append(len(P))
    res = breakPoints(P)
    print(res)
